# Generated by Django 5.1.15 on 2026-04-02 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0060_add_allow_skip_to_task"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="image_unreadable",
            field=models.BooleanField(
                default=False,
                help_text="Whether the image in this task is unreadable or corrupted.",
                verbose_name="image_unreadable",
            ),
        ),
    ]
