# Generated by Django 5.1.15 on 2026-04-02 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0061_task_image_unreadable"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="task_completed",
            field=models.BooleanField(
                default=False,
                help_text="Whether this task has been marked as completed by the annotator.",
                verbose_name="task_completed",
            ),
        ),
    ]
