# Generated by Django 5.1.15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("tasks", "0062_task_task_completed"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="task_verified",
            field=models.BooleanField(
                default=False,
                help_text="Whether this task has been marked as verified.",
                verbose_name="task_verified",
            ),
        ),
        migrations.CreateModel(
            name="TaskVerification",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("verified", models.BooleanField(help_text="True = marked verified, False = unmarked")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "task",
                    models.ForeignKey(
                        help_text="Task this verification event belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="verifications",
                        to="tasks.task",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="User who toggled the verification flag",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="task_verifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
