# Generated by Django 5.1.15 on 2025-12-15 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0033_projects_soft_delete_indexes_async"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProjectTag",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name="project",
            name="tags",
            field=models.ManyToManyField(
                blank=True, related_name="projects", to="projects.projecttag"
            ),
        ),
    ]
