# Generated by Django 5.1.15 on 2025-12-15 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0034_projecttag_project_tags"),
    ]

    operations = [
        migrations.RenameField(
            model_name="project",
            old_name="tags",
            new_name="project_tags",
        ),
    ]
