# Generated by Django 5.1.15 on 2025-12-16 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0035_rename_tags_project_project_tags"),
    ]

    operations = [
        migrations.AlterField(
            model_name="projecttag",
            name="name",
            field=models.CharField(max_length=20),
        ),
    ]
