# Generated by Django 5.1.15 on 2026-04-02 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0036_alter_projecttag_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="show_image_unreadable",
            field=models.BooleanField(
                default=False,
                help_text='Show the "Obraz nieczytelny" flag column in the Data Manager.',
                verbose_name="show image unreadable",
            ),
        ),
    ]
