# Generated by Django 5.1.15 on 2026-04-07 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0037_project_show_image_unreadable"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="is_archived",
            field=models.BooleanField(
                default=False,
                help_text="Whether the project is archived. Archived projects are only visible to admins.",
                verbose_name="is archived",
            ),
        ),
    ]
