# Generated by Django 5.1.15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0038_project_is_archived"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="is_read_only",
            field=models.BooleanField(
                default=False,
                help_text="Whether the project is read-only. Annotations cannot be created, edited, or deleted.",
                verbose_name="is read only",
            ),
        ),
    ]
